### PR TITLE
Use builtin Title and Description

### PR DESCRIPTION
**Pull request by dlford**
Use builtin Title and Description from Ghost admin page instead of manually filling in to partials/about.hbs

### CODE REVIEW

**Comment by andreborud** [comment]
Hello @dlford,
thanks for the pull request. I agree that manually filling `partials/about.hbs` is a big limitation of the theme as it can't be changed through Ghost. 
However I see two problems with your approach, if a blog title is not present which would then show the blog logo would show a logo twice as it is already added to the theme [here](https://github.com/andreborud/penguin-theme-dark/blob/777746f0f886767173b25b0587557c4da6bf5309/default.hbs#L32). That would also remove the blog title from the page title [here](https://github.com/andreborud/penguin-theme-dark/blob/777746f0f886767173b25b0587557c4da6bf5309/default.hbs#L9). 
Then if I instead use a title of the blog then I'm also limited to the title max length which isn´t that long. 
Same goes for description which has its limits in length and doesn't support html or markdown (from what I know). 

Instead it might be possible to create a static page with a slug name like **about** or **welcome** which could be loaded using [{{get}}](https://docs.ghost.org/api/handlebars-themes/helpers/get/#attributes). This would remove limitations on length, would make the content editable from ghost and support markdown/html. What do you think of that?

**Comment by dlford** [comment]
Hi @andreborud,
That makes sense, and seems like a reasonable compromise, thank you for your insight!

**Comment by andreborud** [comment]
@dlford I have updated the theme now to support content from pages. So the content which used to be in about is looking for a page called `landing` and takes the content from there. 
As well as the social media links which will be looking for a page called `social`.

**Comment by dlford** [comment]
@andreborud fantastic, works as expected, thank you!

**Pull request closed without merging**
